<button onclick="return simplePHP.pushPageToHistory('/games/')">
    <i class="fas fa-gamepad"></i>
    <c><?= $t("games") ?></c>
</button>
<button onclick="return simplePHP.pushPageToHistory('/error/')">
    <i class="fas fa-exclamation-circle"></i>
    <c><?= $t("error") ?></c>
</button>
<button onclick="return simplePHP.openModal('login')">
    <i class="fas fa-sign-in-alt"></i>
    <c><?= $t("login") ?></c>
</button>
<button onclick="return simplePHP.openModal('signup')">
    <i class="fas fa-user-plus"></i>
    <c><?= $t("signup") ?></c>
</button>