---
version: "3.7"

services:

  nginx:
    image: dreg.firecow.dk/nginx:${NGINX_TAG}

  php:
    image: dreg.firecow.dk/php:${PHP_TAG}

  sql:
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boom-time
