---
version: "3.7"

services:

  php:
    build: php
    working_dir: /php
    volumes:
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./php:/php

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
    - 3333:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/public:/var/www/html/public

  sql:
    ports:
    - 3316:3306

  npm-install:
    build:
      context: ./
      dockerfile: npm-install/Dockerfile
    container_name: npm-install

  php-dev-cli:
    container_name: php-dev-cli
    build: php-dev-cli
    working_dir: /php
    volumes:
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./php:/php
    - ./php-dev-cli:/shell
    - ./dumps:/dumps

  npm-dev-cli:
    container_name: npm-dev-cli
    image: node:8-alpine
    working_dir: /app/typescript
    volumes:
    - ./:/app
