---
version: "3.7"

services:

  php:
    build: php
    working_dir: /php
    volumes:
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./php:/php

  nginx:
    build:
      context: ./
      dockerfile: nginx/Dockerfile
    ports:
    - 3333:80
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    - ./nginx/public:/var/www/html/public

  sql:
    image: mariadb:10.3.8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: boom-time
    ports:
    - 3316:3306

  php-dev-cli:
    container_name: php-dev-cli
    build: php-dev-cli
    working_dir: /php
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
    - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./php:/php
    - ./php-dev-cli:/shell
    - ./dumps:/dumps
