<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="initial-scale=1">
    <title><?= $d("title") ?></title>
    <link rel="shortcut icon" href="/favicon.png" type="image/x-icon"/>
    <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/style.css">

    <script>
        function submitSpec(event) {
            const xmlHttpRequest = new XMLHttpRequest();
            const formData = new FormData(event.currentTarget);
            xmlHttpRequest.open("POST", "/changespec/", true);
            xmlHttpRequest.send(formData);
            window.location.reload();
        }
    </script>
</head>
<body>

<div class="padding">
    <form action="/armory/" method="get">
        <? foreach ($d("specs") as $spec): ?>
        <div style="display:inline-block;">
            <input onclick="this.form.submit()" style="position:absolute; margin-left:20px; margin-top: 20px;" type="checkbox" name="specs[]" value="<?= $spec['specId']; ?>" <?= $spec['checkedAttr'] ?>/>
            <img alt="<?= $spec['specName'] ?>" style="border-radius: 2px; border: 1px solid rgba(255, 255, 255, 0.7)" width="32" height="32" src="/icons/<?= $spec["icon"] ?>">
        </div>
        <? endforeach; ?>
        <div style="display: inline-block; margin-left: 20px;"></div>
        <? foreach ($d("locations") as $i => $location): ?>
        <div style="display:inline-block;">
        <input onclick="this.form.submit()" style="position:absolute; margin-left:20px; margin-top: 20px;" type="checkbox" name="locations[]" value="<?= $location['name']; ?>" <?= $location['checkedAttr'] ?>/>
        <img style="border-radius: 2px; border: 1px solid rgba(255, 255, 255, 0.7)" width="32" height="32" src="/icons/<?= $location["icon"] ?>">
        </div>
        <? endforeach; ?>
    </form>
</div>

<table>
    <tr>
        <th></th>
        <? foreach ($d("chars") as $char): ?>
        <th>
            <div class="text-ellipsis" style="display: inline-block; width: 226px;">
                <span style="color:<?= $char['classColor']; ?>;"><?= $char['charName']; ?></span>
                <span>(<?= $d("getItemsCount")($char['charName']) ?>)</span>
            </div>
            <div style="display: inline-block">
            <!--<form method="post" id="specForm" onchange="submitSpec(event);">
                <select name="newSpecId">
                    <?/* foreach ($d("specs") as $spec): */?>
                        <option value="<?/*= $spec['specId'] */?>" <?/*= $spec['selectedAttr'] */?>><?/*= $spec['specName'] */?></option>
                    <?/* endforeach; */?>
                </select>
                <input name="charName" value="<?/*= $charName; */?>" hidden/>
            </form>-->
            </div>
        </th>
        <? endforeach; ?>
    </tr>
    <? foreach ($d("types") as $type): ?>
    <tr>
        <th><div class="padding"><?= $d("groupNames")[$type['group']] ?></div></th>
        <? foreach ($d("chars") as $chars): ?>


        <td valign="middle">
            <? foreach ($d("getItems")($chars['charName'], $type['group']) as $item): ?>
            <div style="padding:1px; display: flex; align-items: center;">
                <img style="border-radius: 2px; border: 1px solid <?= $item['color'] ?>; margin-right:4px;" width="18" height="18" src="/icons/<?= $item["icon"] ?>.jpg">
                <div class="text-ellipsis" style="width: 150px;display: inline-block;"><?= $item["itemName"] ?></div>
                <? if ($item["enchant"] != null) :?>
                <div class="text-ellipsis" style="width: 50px;display: inline-block; color: #31ff3c; font-size: 9px;"><?= $item["enchantName"] ?></div>
                <? endif; ?>
            </div>
            <? endforeach; ?>
        </td>
        <? endforeach; ?>
    </tr>
    <? endforeach ?>
</table>

</body>
</html>