<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="initial-scale=1">
    <title><?= $d("title") ?></title>
    <link rel="shortcut icon" href="/favicon.png" type="image/x-icon"/>
    <link href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="/style.css">
</head>
<body>

<div class="padding">
    <form action="/armory/" method="get">
        <select name="classId" onchange="this.form.submit()">
            <? foreach ($d("classes") as $class): ?>
            <option value="<?= $class['classId'] ?>" <?= $class['selectedAttr'] ?>><?= $class['className'] ?></option>
            <? endforeach; ?>
        </select>
        <? if ($d("specCount") > 0) : ?>
        <!--<select name="specId" onchange="this.form.submit()">
            <?/* foreach ($d("specs") as $spec): */?>
            <option value="<?/*= $spec['specId'] */?>" <?/*= $spec['selectedAttr'] */?>><?/*= $spec['specName'] */?></option>
            <?/* endforeach; */?>
        </select>-->
        <? endif; ?>
    </form>
</div>

<table>
    <tr>
        <th></th>
        <? foreach ($d("charNames") as $charName): ?>
        <th><div class="small-capped"><?= $charName; ?></div></th>
        <? endforeach; ?>
    </tr>
    <? foreach ($d("types") as $type): ?>
    <tr>
        <th><div class="padding"><?= $d("groupNames")[$type['group']] ?></div></th>
        <? foreach ($d("charNames") as $charName): ?>
        <td valign="top">
            <? foreach ($d("getItems")($charName, $type['group']) as $item): ?>
            <div class="small-capped"><img style="vertical-align: middle; border-radius: 2px; border: 1px solid <?= $item['color'] ?>; margin-right:4px;" width="18" height="18" src="/icons/<?= $item["icon"] ?>.jpg"><?= $item["itemName"] ?></div>
            <? endforeach; ?>
        </td>
        <? endforeach; ?>
    </tr>
    <? endforeach ?>
</table>

</body>
</html>