<!DOCTYPE html>
<html lang="en">
<head>

    <meta name="viewport" content="initial-scale=1">
    <title><?= $d("title") ?></title>
    <link rel="shortcut icon" href="/favicon.png" type="image/x-icon"/>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.4.1/semantic.css">
    <link rel="stylesheet" type="text/css" href="/style.css">
</head>
<style>

</style>
<body>
<form class="padding maxWidth" id="form" action="/wowclassicformula/" method="get">
    <div class="ui input maxWidth">
        <input type="text" name="formula" placeholder="Formula..." value="<?= $d("formula") ?>">
    </div>
</form>
<? foreach ($d("slots") as $slot) : ?>
<div style="display:inline-block;">
    <div style="margin:5px;"><?= $slot ?></div>
    <table style="margin:5px;">
        <tr>
            <th>ItemName</th>
        </tr>
        <? foreach ($d("getItemsBySlot")($slot) as $item) : ?>
        <tr>
            <td><?= $item['itemName'] ?></td>
        </tr>
        <? endforeach; ?>
    </table>
</div>
<? endforeach; ?>
</body>
</html>