<html>
<head>
    <meta name="viewport" content="initial-scale=1">
    <title>Oh Snap</title>
    <link rel="shortcut icon" href="/favicon.png" type="image/x-icon"/>
    <link rel="stylesheet" type="text/css" href="/style.css">
</head>
<body>

<div class="padding">
    <h3>Error !!</h3>
    <div style="white-space: pre-wrap; font-size: var(--smallsize);"><?= $d('pretty') ?></div>
</div>

</body>
</html>